# location.py
"""
Centralized metadata for Rwanda administrative columns.
Used for dynamic merging of REDCap location variables.
"""

# ---------------- DISTRICT COLUMNS ----------------
DISTRICT_COLUMNS = [
    'akarere_utuyemo1_e',
    'akarere_utuyemo2_w',
    'akarere_utuyemo3_n',
    'akarere_utuyemo4_s',
    'akarere_utuyemo5_k',
]

# ---------------- SECTOR COLUMNS ----------------
SECTOR_COLUMNS = [
    'umurenge_bugesera',
    'umurenge_gatsibo',
    'umurenge_kirehe',
    'umurenge_kayonza',
    'umurenge_nyagatare',
    'umurenge_ngoma',
    'umurenge_rwamagana',
    "umurenge_kicukiro",
    "umurenge_gasabo",
    "umurenge_nyarugenge",
    "umurenge_burera",
    "umurenge_gakenke",
    "umurenge_utu_n_musanz",
    "umurenge_utu_gicu",
    "umurenge_rulindo",
    "umurenge_karongi",
    "umurenge_ngororero",
    "umurenge_nyabihu",
    "umurenge_nyamasheke",
    "umurenge_rubavu",
    "umurenge_rusizi",
    "umurenge_rutsiro",
    "umurenge_gisagara",
    "umurenge_kamonyi",
    "umurenge_ruhango",
    "umurenge_muhanga",
    "umurenge_nyanza",
    "umurenge_huye",
    "umurenge_nyamagabe",
    "umurenge_nyaruguru",
]

# ---------------- CELL COLUMNS ----------------
# Keep all cell-related REDCap variables here
CELL_COLUMNS =  ['utugari_two_muri_gashora_b',
       'utugari_two_muri_juru_buge', 'utugari_two_muri_kamabuye',
       'utugari_two_muri_mareba_bu', 'utugari_two_muri_mayange_b',
       'utugari_two_muri_musenyi_b', 'utugari_two_muri_mwogo_bug',
       'utugari_two_muri_ngeruka_b', 'utugari_two_muri_ntarama_b',
       'utugari_two_muri_nyamata_b', 'utugari_two_muri_nyarugeng',
       'utugari_two_muri_rilima_bu', 'utugari_two_muri_ruhuha_bu',
       'utugari_two_muri_rweru_bug', 'utugari_two_muri_shyara_bu',
       'utugari_two_muri_gasange_g',
       'utugari_two_muri_gatsibo_g', 'utugari_two_muri_gitoki_ga',
       'utugari_two_muri_kabarore', 'utugari_two_muri_kageyo_ga',
       'utugari_two_muri_kiramuruz', 'utugari_two_muri_kiziguro',
       'utugari_two_muri_muhura_ga', 'utugari_two_muri_murambi_g',
       'utugari_two_muri_ngarama_g', 'utugari_two_muri_nyagihang',
       'utugari_two_muri_remera_ga', 'utugari_two_muri_rwimbogo',
       'utugari_two_muri_rugarama', 
       'utugari_two_muri_gahini_ka', 'utugari_two_muri_kabare_ka',
       'utugari_two_muri_kabarondo', 'utugari_two_muri_mukarange',
       'utugari_two_muri_murama_ka', 'utugari_two_muri_murundi_k',
       'utugari_two_muri_mwili_kay', 'utugari_two_muri_ndego_kay',
       'utugari_two_muri_nyamirama', 'utugari_two_muri_rukara_ka',
       'utugari_two_muri_ruramira', 'utugari_two_muri_rwinkwavu',
       'utugari_two_muri_gahara_ki',
       'utugari_two_muri_gatore_ki', 'utugari_two_muri_kigarama',
       'utugari_two_muri_kigina_ki', 'utugari_two_muri_kirehe_ki',
       'utugari_two_muri_mahama_ki', 'utugari_two_muri_mpanga_ki',
       'utugari_two_muri_musaza_ki', 'utugari_two_muri_mushikiri',
       'utugari_two_muri_nasho_kir', 'utugari_two_muri_nyamugari',
       'utugari_two_muri_nyarubuye',
       'utugari_two_muri_gashanda', 'utugari_two_muri_jarama_ng',
       'utugari_two_muri_karembo_n', 'utugari_two_muri_kazo_ngom',
       'utugari_two_muri_kibungo_n', 'utugari_two_muri_mugesera',
       'utugari_two_muri_murama_ng', 'utugari_two_muri_mutenderi',
       'utugari_two_muri_remera_ng', 'utugari_two_muri_rukira_ng',
       'utugari_two_muri_rukumberi', 'utugari_two_muri_rurenge_n',
       'utugari_two_muri_sake_ngom', 'utugari_two_muri_zaza_ngom',
       'utugari_two_muri_gatunda_n',
       'utugari_two_muri_karama_ny', 'utugari_two_muri_karangazi',
       'utugari_two_muri_katabagem', 'utugari_two_muri_kiyombe_n',
       'utugari_two_muri_matimba_n', 'utugari_two_muri_mimuri_ny',
       'utugari_two_muri_mukama_ny', 'utugari_two_muri_musheri_n',
       'utugari_two_muri_nyagatare', 'utugari_two_muri_rukomo_ny',
       'utugari_two_muri_rwempasha', 'utugari_two_muri_rwimiyaga',
       'utugari_two_muri_tabagwe_n',
       'utugari_two_muri_fumbwe_rw', 'utugari_two_muri_gahengeri',
       'utugari_two_muri_gishari_r', 'utugari_two_muri_karenge_r',
       'utugari_two_muri_kigabiro', 'utugari_two_muri_muhazi_rw',
       'utugari_two_muri_munyaga_r', 'utugari_two_muri_munyiginy',
       'utugari_two_muri_musha_rwa', 'utugari_two_muri_muyumbu_r',
       'utugari_two_muri_mwulire_r', 'utugari_two_muri_nyakaliro',
       'utugari_two_muri_nzige_rwa', 'utugari_two_muri_rubona_rw',
       'utugari_two_muri_bwishyura',
       'utugari_two_muri_gashari_k', 'utugari_two_muri_gishyita',
       'utugari_two_muri_gitesi_ka', 'utugari_two_muri_mubuga_ka',
       'utugari_two_muri_murambi_k', 'utugari_muri_murundi_karongi',
       'utugari_two_muri_mutuntu_k', 'utugari_two_muri_rubengera',
       'utugari_two_muri_rugabano', 'utugari_two_muri_ruganda_k',
       'utugari_two_muri_rwankuba', 'utugari_two_muri_twumba_ka',
       'utugari_two_muri_bwira_ngo',
       'utugari_two_muri_gatumba_n', 'utugari_two_muri_hindiro_n',
       'utugari_two_muri_kabaya_ng', 'utugari_two_muri_kageyo_ng',
       'utugari_two_muri_kavumu_ng', 'utugari_two_muri_matyazo_n',
       'utugari_two_muri_muhanda_n', 'utugari_two_muri_muhororo',
       'utugari_two_muri_ndaro_ngo', 'utugari_two_muri_ngororero',
       'utugari_two_muri_nyange_ng', 'utugari_two_muri_sovu_ngor',
       'utugari_two_muri_arusha_ny',
       'utugari_two_muri_jenda_nya', 'utugari_two_muri_jomba_nya',
       'utugari_two_muri_kabatwa_n', 'utugari_two_muri_karago_ny',
       'utugari_two_muri_kintobo_n', 'utugari_two_muri_mukamira',
       'utugari_two_muri_muringa_n', 'utugari_two_muri_rambura_n',
       'utugari_two_muri_rugera_ny', 'utugari_two_muri_rurembo_n',
       'utugari_two_muri_shyira_ny', 
       'utugari_two_muri_bushekeri', 'utugari_two_muri_bushenge',
       'utugari_two_muri_cyato_nya', 'utugari_two_muri_gihombo_n',
       'utugari_two_muri_kagano_ny', 'utugari_two_muri_kanjongo',
       'utugari_two_muri_karambi_n', 'utugari_two_muri_karengera',
       'utugari_two_muri_kirimbi_n', 'utugari_two_muri_macuba_ny',
       'utugari_two_muri_mahembe_n', 'utugari_two_muri_nyabiteke',
       'utugari_two_muri_rangiro_n', 'utugari_two_muri_ruharambu',
       'utugari_two_muri_shangi_ny', 
       'utugari_two_muri_bugeshi_r', 'utugari_two_muri_busasaman',
       'utugari_two_muri_cyanzarwe', 'utugari_two_muri_gisenyi_r',
       'utugari_two_muri_kanama_ru', 'utugari_two_muri_kanzenze',
       'utugari_two_muri_mudende_r', 'utugari_two_muri_nyakiriba',
       'utugari_two_muri_nyamyumba', 'utugari_two_muri_nyundo_ru',
       'utugari_two_muri_rubavu_ru', 'utugari_two_muri_rugerero',
       'utugari_two_muri_bugarama',
       'utugari_two_muri_butare_ru', 'utugari_two_muri_bweyeye_r',
       'utugari_two_muri_gashonga', 'utugari_two_muri_giheke_ru',
       'utugari_two_muri_gihundwe', 'utugari_two_muri_gikundamv',
       'utugari_two_muri_gitambi_r', 'utugari_two_muri_kamembe_r',
       'utugari_two_muri_muganza_r', 'utugari_two_muri_mururu_ru',
       'utugari_two_muri_nkanka_ru', 'utugari_two_muri_nkombo_ru',
       'utugari_two_muri_nkungu_ru', 'utugari_two_muri_ryakabuye',
       'utugari_two_muri_nyakarenz', 'utugari_two_muri_nzahaha_r',
       'utugari_muri_rwimbogo', 
       'utugari_two_muri_boneza_ru', 'utugari_two_muri_gihango_r',
       'utugari_two_muri_kigeyo_ru', 'utugari_two_muri_kivumu_ru',
       'utugari_two_muri_manihira', 'utugari_two_muri_mukuru_ru',
       'utugari_two_muri_murunda_r', 'utugari_two_muri_musasa_ru',
       'utugari_two_muri_mushonyi', 'utugari_two_muri_mushubati',
       'utugari_two_muri_nyabirasi', 'utugari_two_muri_ruhango_r',
       'utugari_two_muri_rusebeya', 
       'utugari_two_muri_bungwe_bu', 'utugari_two_muri_butaro_bu',
       'utugari_two_muri_cyanika_b', 'utugari_two_muri_cyeru_bur',
       'utugari_two_muri_gahunga_b', 'utugari_two_muri_gatebe_bu',
       'utugari_two_muri_gitovu_bu', 'utugari_two_muri_kagogo_bu',
       'utugari_two_muri_kinoni_bu', 'utugari_two_muri_kinyababa',
       'utugari_two_muri_kivuye_bu', 'utugari_two_muri_nemba_bur',
       'utugari_two_rugarama', 'utugari_two_muri_rugendaba',
       'utugari_two_muri_ruhunde_b', 'utugari_two_muri_rusarabuy',
       'utugari_two_muri_rwerere_b', 
       'utugari_two_muri_busengo_g', 'utugari_two_muri_coko_gake',
       'utugari_two_muri_cyabingo', 'utugari_two_muri_minazi_ga',
       'utugari_two_muri_rusasa_ga', 'utugari_two_muri_gashenyi',
       'utugari_two_muri_karambo_g', 'utugari_two_muri_kamubuga',
       'utugari_two_muri_mataba_ga', 'utugari_two_muri_gakenke_g',
       'utugari_two_muri_muzo_gake', 'utugari_two_muri_muyongwe',
       'utugari_two_muri_muhondo_g', 'utugari_two_muri_nemba_gak',
       'utugari_two_muri_mugunga_g', 'utugari_two_muri_ruli_gake',
       'utugari_two_muri_janja_gak', 'utugari_two_muri_kivuruga',
       'utugari_two_muri_rushashi', 
       'utugari_two_muri_bukure_gi', 'utugari_two_muri_bwisige_g',
       'utugari_two_muri_byumba_gi', 'utugari_two_muri_centre_ga',
       'utugari_two_muri_cyumba_gi', 'utugari_two_muri_giti_gicu',
       'utugari_two_muri_kageyo_gi', 'utugari_two_muri_kaniga_gi',
       'utugari_two_muri_manyagiro', 'utugari_two_muri_miyove_gi',
       'utugari_muri_mukarange', 'utugari_two_muri_muko_gicu',
       'utugari_two_muri_mutete_gi', 'utugari_two_muri_nyamiyaga',
       'utugari_two_muri_nyankenke', 'utugari_two_muri_rubaya_gi',
       'utugari_two_muri_rukomo_gi', 'utugari_two_muri_rushaki_g',
       'utugari_two_muri_rutare_gi', 'utugari_two_muri_ruvune_gi',
       'utugari_two_muri_rwamiko_g', 'utugari_two_muri_shangasha',
       'utugari_two_muri_busogo_mu',
       'utugari_two_muri_cyuve_mus', 'utugari_two_muri_gacaca_mu',
       'utugari_two_muri_gashaki_m', 'utugari_two_muri_gataraga',
       'utugari_two_muri_kimonyi_m', 'utugari_two_muri_kinigi_mu',
       'utugari_two_muri_muhoza_mu', 'utugari_two_muri_muko_musa',
       'utugari_two_muri_musanze_m', 'utugari_two_muri_nkotsi_mu',
       'utugari_two_muri_nyange_mu', 'utugari_two_muri_remera_mu',
       'utugari_two_muri_rwaza_mus', 'utugari_two_muri_shingiro',
       'utugari_two_muri_base_ruli',
       'utugari_two_muri_burega_mu', 'utugari_two_muri_bushoki_m',
       'utugari_two_muri_buyoga_mu', 'utugari_two_muri_cyinzuzi',
       'utugari_two_muri_cyungo_ru', 'utugari_two_muri_kinihira',
       'utugari_two_muri_kisaro_ru', 'utugari_two_muri_masoro_ru',
       'utugari_two_muri_mbogo_rul', 'utugari_two_muri_murambi_r',
       'utugari_two_muri_ngoma_rul', 'utugari_two_muri_ntarabana',
       'utugari_two_muri_rukozo_ru', 'utugari_two_muri_rusiga_ru',
       'utugari_two_muri_shyorongi', 'utugari_two_muri_tumba_rul',
       'utugari_two_muri_gikonko_g',
       'utugari_two_muri_gishubi_g', 'utugari_two_muri_kansi_gis',
       'utugari_two_muri_kibirizi', 'utugari_two_muri_kigembe_g',
       'utugari_two_muri_mamba_gis', 'utugari_two_muri_muganza_g',
       'utugari_two_muri_mugombwa', 'utugari_two_muri_mukindo_g',
       'utugari_two_muri_musha_gis', 'utugari_two_muri_ndora_gis',
       'utugari_two_muri_nyanza_gi', 'utugari_two_muri_save_gisa',
       'utugari_two_muri_gishamvu',
       'utugari_two_muri_huye_huye', 'utugari_two_muri_karama_hu',
       'utugari_two_muri_kigoma_hu', 'utugari_two_muri_kinazi_hu',
       'utugari_two_muri_maraba_hu', 'utugari_two_muri_mbazi_huy',
       'utugari_two_muri_mukura_hu', 'utugari_two_muri_ngoma_huy',
       'utugari_two_muri_ruhashya', 'utugari_two_muri_rusatira',
       'utugari_two_muri_rwaniro_h', 'utugari_two_muri_simbi_huy',
       'utugari_two_muri_tumba_huy', 
       'utugari_two_muri_gacurabwe', 'utugari_two_muri_karama_ka',
       'utugari_two_muri_kayenzi_k', 'utugari_two_muri_kayumbu_k',
       'utugari_two_muri_mugina_ka', 'utugari_two_muri_musambira',
       'utugari_two_muri_ngamba_ka', 'utugari_muri_nyamiyaga',
       'utugari_two_muri_nyarubaka', 'utugari_two_muri_rugarika',
       'utugari_two_muri_rukoma_ka', 'utugari_two_muri_runda_kam',
       'utugari_two_muri_cyeza_muh',
       'utugari_two_muri_kabacuzi', 'utugari_two_muri_kibangu_m',
       'utugari_two_muri_kiyumba_m', 'utugari_two_muri_muhanga_m',
       'utugari_two_muri_mushishir', 'utugari_two_muri_nyabinoni',
       'utugari_two_muri_nyamabuye', 'utugari_two_muri_nyarusang',
       'utugari_two_muri_rongi_muh', 'utugarmuri_rugendaba',
       'utugari_two_muri_shyogwe_m', 
       'utugari_two_muri_buruhukir', 'utugari_two_muri_cyanika_n',
       'utugari_two_muri_gatare_ny', 'utugari_two_muri_kaduha_ny',
       'utugari_two_muri_kamegeri', 'utugari_two_muri_kibilizi',
       'utugari_two_muri_kibumbwe', 'utugari_two_muri_kitabi_ny',
       'utugari_two_muri_mbazi_nya', 'utugari_two_muri_mugano_ny',
       'utugari_two_muri_musange_n', 'utugari_two_muri_musebeya',
       'utugari_two_muri_mushubi_n', 'utugari_two_muri_nkomane_n',
       'utugari_two_muri_gasaka_ny', 'utugari_two_muri_tare_nyam',
       'utugari_two_muri_uwinkingi',
       'utugari_muri_busasaman', 'utugari_two_muri_busoro_ny',
       'utugari_two_muri_cyabakamy', 'utugari_muri_kibirizi',
       'utugari_two_muri_kigoma_ny', 'utugari_two_muri_gatagara',
       'utugari_two_muri_rwabicuma', 'utugari_two_muri_muyira_ny',
       'utugari_two_muri_ntyazo_ny', 'utugari_two_muri_nyagisozi',
       'utugari_two_muri_cyahinda',
       'utugari_two_muri_busanze_n', 'utugari_two_muri_kibeho_ny',
       'utugari_two_muri_mata_nyar', 'utugari_two_muri_munini_ny',
       'utugari_two_muri_kivu_nyar', 'utugari_two_muri_ngera_nya',
       'utugari_two_muri_ngoma_nya', 'utugari_two_muri_nyabimata',
       'utugari_muri_nyagisozi', 'utugari_two_muri_ruheru_ny',
       'utugari_two_muri_muganza_n', 
       'utugari_two_muri_ruramba_n','utugari_two_muri_rusenge_n', 
       'utugari_two_muri_bweramana', 'utugari_two_muri_byimana_r',
       'utugari_two_muri_kabagari', 'utugari_two_muri_kinazi_ru',
       'utugari_twa_kinihira', 'utugari_two_muri_mbuye_ruh',
       'utugari_two_muri_mwendo_ru', 'utugari_two_muri_ntongwe_r',
       'utugari_muri_ruhango_r', 
       'utugari_two_muri_bumbogo_g', 'utugari_two_muri_gatsata_g',
       'utugari_two_muri_gikomero', 'utugari_two_muri_gisozi_ga',
       'utugari_two_muri_jabana_ga', 'utugari_two_muri_jali_gasa',
       'utugari_two_muri_kacyiru_g', 'utugari_two_muri_kimihurur',
       'utugari_two_muri_kimironko', 'utugari_two_muri_kinyinya',
       'utugari_two_muri_ndera_gas', 'utugari_two_muri_nduba_gas',
       'utugari_remera_gasabo', 'utugari_two_muri_rusororo',
       'utugari_two_muri_rutunga_g', 
       'utugari_two_muri_gahanga_k', 'utugari_two_muri_gatenga_k',
       'utugari_two_muri_gikondo_k', 'utugari_two_muri_kagarama',
       'utugari_two_muri_kanombe_k', 'utugari_two_muri_kicukiro',
       'utugari_muri_kigarama', 'utugari_two_muri_masaka_ki',
       'utugari_two_muri_niboye_ki', 'utugari_two_muri_nyarugung',
       'utugari_two_muri_gitega_ny',
       'utugari_two_muri_kanyinya', 'utugari_two_muri_kigali_ny',
       'utugari_two_muri_kimisagar', 'utugari_two_muri_magerager',
       'utugari_two_muri_muhima_ny', 'utugari_two_muri_nyakaband',
       'utugari_two_muri_nyamiramb', 'utugari_two_muri_rwezameny',
       'utugari_muri_nyarugeng',]

def get_existing_columns(dataframe, column_list):
    """
    Returns only columns that exist in dataframe.
    Prevents KeyErrors during merging.
    """
    return [col for col in column_list if col in dataframe.columns]


# -------------------------------------------------------------------------------------------------------------------------------------------------------------------
# --------------------------------------------------------------------------------------------------------------------------------------------------------------------
